# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df1ed7b794f7500e357c156e56d94e573f3134eec0adb0ba07111ae6d9c5a4403033f41ee612b15cef523334531049d336dd4c53505affe4e9d474d1828d3c60

test:
  secret_key_base: 60eac86aef18029dc424ac9afc9b46c3e4337c7987c4f79c35940dc9a4cf53b67f34b069b055a332b28ed4b63244dd696192c8155b133df46e85804a81868473

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
